{
 "title": "ginkgo Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "logger" },
   { "name": "level" },
   { "name": "examplefoo" }
  ]
 },
 "panels": [
  {
   "title": "Ginkgo Node",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (ginkgo_spec{type=\"NodeTypeIt\"} != 4) by (node,type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Example Ready Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_join(\n  sum (\n    kube_customresource_example_status{type=\"Ready\"}\n  ) by (\n    kind, name, namespace, status,\n  ),\n  \"name_namespace\", \"/\", \"namespace\", \"name\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ExampleFoo Ready Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_join(\n  sum (\n    kube_customresource_examplefoo_status{type=\"Ready\"}\n  ) by (\n    kind, name, namespace,\n  ),\n  \"name_namespace\", \"/\", \"namespace\", \"name\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ginkgo Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"e2e-observability\"} | json | examplefoo=~\"$examplefoo\" | logger=~\"$logger\" | level=~\"$level\" | line_format \"{{ .ts }} \\033[1;37m{{ .level }}\\033[0m {{ .logger }} {{ .msg }}\""
    }
   ]
  }
 ]
}